version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    expose:
      - 3309
