"""Add modified_on to services table

Revision ID: d3bdae443a1a
Revises: 727577283159
Create Date: 2022-04-20 15:02:20.897119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bdae443a1a'
down_revision = '727577283159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('modified_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'modified_on')
    # ### end Alembic commands ###
